-- Migration: Project soft-delete cascade cleanup trigger
-- Day Zero OS V1.0

CREATE OR REPLACE FUNCTION public.handle_project_soft_delete()
RETURNS TRIGGER AS $$
BEGIN
  -- Idempotency guard: execute ONLY when deleted_at transitions from NULL to a non-null timestamp
  IF NEW.deleted_at IS NOT NULL AND OLD.deleted_at IS NULL THEN
    -- Delete all child entities associated with the soft-deleted project
    DELETE FROM public.milestones WHERE project_id = NEW.id;
    DELETE FROM public.project_tasks WHERE project_id = NEW.id;
    DELETE FROM public.project_bugs WHERE project_id = NEW.id;
    DELETE FROM public.technical_debt_items WHERE project_id = NEW.id;
    DELETE FROM public.project_repositories WHERE project_id = NEW.id;
    DELETE FROM public.development_notes WHERE project_id = NEW.id;
    DELETE FROM public.content_items WHERE project_id = NEW.id;
    DELETE FROM public.architecture_decisions WHERE project_id = NEW.id;
    DELETE FROM public.notifications WHERE project_id = NEW.id;
    DELETE FROM public.ai_sessions WHERE project_id = NEW.id;
    DELETE FROM public.assets WHERE project_id = NEW.id;
    
    -- Disassociate knowledge entries so they become global/unassigned entries
    UPDATE public.knowledge_entries SET project_id = NULL WHERE project_id = NEW.id;

    -- Delete activity_logs LAST so any logs generated by child entity DELETE triggers are cleaned up
    DELETE FROM public.activity_logs WHERE project_id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Drop existing trigger if present for idempotency
DROP TRIGGER IF EXISTS trigger_handle_project_soft_delete ON public.projects;

-- Bind trigger to public.projects AFTER UPDATE OF deleted_at
CREATE TRIGGER trigger_handle_project_soft_delete
  AFTER UPDATE OF deleted_at ON public.projects
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_project_soft_delete();

NOTIFY pgrst, 'reload schema';
